"use client";
import {useState} from "react"; import {useLocale,useTranslations} from "next-intl"; import {motion,useReducedMotion} from "framer-motion"; import {Apple,Check,ChevronDown} from "lucide-react"; import type {Locale} from "../../i18n"; import {appStoreUrl} from "./app-store";
export default function HeroV2(){const t=useTranslations("v2"),locale=useLocale() as Locale,[done,setDone]=useState<number[]>([]),reduce=useReducedMotion();const tasks=t.raw("hero.demoTasks") as string[];const toggle=(i:number)=>setDone(x=>x.includes(i)?x.filter(v=>v!==i):[...x,i]);return <section className="v2-hero"><div className="hero-glow hero-glow-a"/><div className="hero-glow hero-glow-b"/><div className="v2-container relative grid min-h-[92svh] items-center gap-14 pb-20 pt-28 lg:grid-cols-[1.05fr_.95fr]">
 <div><div className="v2-kicker">{t("hero.kicker")}</div><h1 className="hero-title mt-6">{t("hero.h1")}</h1><p className="mt-6 max-w-xl text-base leading-[1.9] text-muted sm:text-lg">{t("hero.sub")}</p><div className="mt-8 flex flex-wrap items-center gap-3"><a href={appStoreUrl(locale)} target="_blank" rel="noreferrer" className="app-store-badge"><Apple fill="currentColor" size={27}/><span><small>Download on the</small><strong>App Store</strong></span></a><span className="soon-pill">{t("playSoon")}</span></div><p className="mt-5 text-sm font-bold text-muted">{t("hero.trust")}</p></div>
 <div className="relative mx-auto w-full max-w-[480px]"><div className="demo-label">{t("hero.demoLabel")}</div><div className="demo-card"><div className="mb-5 flex items-center justify-between"><span className="font-bold">Today</span><span className="text-sm text-muted">{done.length} / 3</span></div>{tasks.map((task,i)=><button key={task} onClick={()=>toggle(i)} className="demo-task"><motion.span animate={{scale:done.includes(i)?[1,.78,1]:1}} transition={{type:"spring",stiffness:500,damping:30}} className={`demo-check ${done.includes(i)?"done":""}`}>{done.includes(i)&&<Check size={15}/>}</motion.span><span className={done.includes(i)?"line-through text-muted":""}>{task}</span></button>)}
 {done.length===3&&<motion.div initial={reduce?false:{opacity:0,y:10}} animate={{opacity:1,y:0}} className="demo-complete"><p className="font-bold">{t("hero.demoDone")}</p><button onClick={()=>setDone([])}>{t("hero.reset")}</button></motion.div>}</div></div>
 <motion.a href="#statement" className="scroll-cue" animate={reduce?{}:{y:[0,8,0]}} transition={{duration:2,repeat:Infinity}}><span>{t("scroll")}</span><ChevronDown size={16}/></motion.a>
 </div></section>}

